name: Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install
        run: yarn --no-progress --non-interactive --no-lockfile
      - name: Alex
        run: yarn alex
